export const FETCH_PRAYING_THREEDAY = 'FETCH_PRAYING_THREEDAY';
export const FETCH_TODAY_PRAYTIME = 'FETCH_TODAY_PRAYTIME';
export const FETCH_PRAYTIME_BYDATE = 'FETCH_PRAYTIME_BYDATE';
export const FETCH_CURRENT_MONTHPRAYTIME = 'FETCH_CURRENT_MONTHPRAYTIME';
export const FETCH_CURRENT_MONTHPRAYTIME_CITY = 'FETCH_CURRENT_MONTHPRAYTIME_CITY';
export const FETCH_PRAYTIME_BY_YYYYMM = 'FETCH_PRAYTIME_BY_YYYYMM';