export const FETCH_DISPLAYALL_FORUM_BYUSER = 'FETCH_DISPLAYALL_FORUM_BYUSER';
export const CREATE_FORUM = 'CREATE_FORUM';
export const POST_COMMENT = 'POST_COMMENT';
export const EDIT_COMMENT = 'EDIT_COMMENT';
export const CLOSE_FORUM = 'CLOSE_FORUM';
export const DISPLAY_FORUM_DETAIL = 'DISPLAY_FORUM_DETAIL';